import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author cloud
 */
public class Calculator extends javax.swing.JFrame {
    
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        allClear();
        updateDisplay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        display = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextField9 = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jFormattedTextField7 = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jFormattedTextField8 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextField10 = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton23 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        quit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));

        display.setEditable(false);
        display.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        display.setText("Player Fantasy Total: ");
        display.setToolTipText("");
        display.setMargin(new java.awt.Insets(15, 15, 15, 15));
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });
        getContentPane().add(display, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(11, 2));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Receiving Yards:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2);

        jFormattedTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jFormattedTextField9);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Passing Yards:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel3);

        jFormattedTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jFormattedTextField1);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Rushing Yards:");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel4);

        jFormattedTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jFormattedTextField3);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Interceptions:");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel5);

        jFormattedTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jFormattedTextField2);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Touchdown Passes:");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel6);

        jFormattedTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jFormattedTextField4);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Touchdown Caught:");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel7);

        jFormattedTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jFormattedTextField5);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Touchdown Run:");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel8);

        jFormattedTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jFormattedTextField6);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Two Point Conversion:");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel9);

        jFormattedTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jFormattedTextField7);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Fumbles:");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel10);

        jFormattedTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jFormattedTextField8);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Receptions:");
        jPanel1.add(jLabel1);

        jFormattedTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jFormattedTextField10);
        jPanel1.add(jLabel11);

        jButton23.setText("Compute Total");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton23);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        jMenuItem1.setText("Change Ruleset");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        quit.setText("Quit");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        jMenu1.add(quit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        about.setText("About");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        jMenu2.add(about);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    Ruleset ruleset = new Ruleset();
    Player player = new Player("", "Offense");
    Team team = new Team("testTeam", 0001);
    
    private double result ;
    double[] scores = new double[10]; 
    private boolean error ;
    private int displayLen ;
    private String disp ;
    public static final int MAX_DISPLAY_LEN = 5;
    public static final double MAX_VALUE_EXCLUSIVE = 1000.0;
    private void allClear ()
    {
        result = 0.0;
        error = false ;
        displayLen = 0;
        disp = " " ;
    }
// Avoids " scientific notation " format for large numbers ;
// and guaranteed to give us too many digits . We then just
// truncate away the ones we don 't need .
    private String toDisplayString ( double d )
    {
    String asStr = String.format("%." + (MAX_DISPLAY_LEN) + "f", d);
    int maxLen = MAX_DISPLAY_LEN ;
    if(asStr.charAt (0) == '-') {maxLen += 1;}
    asStr = asStr.substring(0,maxLen);
    return asStr;
    }
private void updateDisplay ()
{
if ( error )
{
display . setText ( " Err " ) ;
}
else if( displayLen > 0)
{
display . setText ( "Player Fantasy Total: " + disp ) ;
}
else
{
display . setText ( "Player Fantasy Total: " + toDisplayString ( result ) ) ;
}
}


    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(jPanel1, "Created by Ryan Funke. For changing ruleset, click button once for PPR, twice for 0.5 PPR, or three times to reset to standard.");
    }//GEN-LAST:event_aboutActionPerformed

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_quitActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayActionPerformed

    private void jFormattedTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField3ActionPerformed

    private void jFormattedTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField6ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        
        
        if (jFormattedTextField9.getText().length() == 0)
        {jFormattedTextField9.setText("0");}
        if (jFormattedTextField1.getText().length() == 0)
        {jFormattedTextField1.setText("0");}
        if (jFormattedTextField3.getText().length() == 0)
        {jFormattedTextField3.setText("0");}
        if (jFormattedTextField2.getText().length() == 0)
        {jFormattedTextField2.setText("0");}
        if ((jFormattedTextField4.getText().length()) == 0)
        {jFormattedTextField4.setText("0");}
        if (jFormattedTextField5.getText().length() == 0)
        {jFormattedTextField5.setText("0");}
        if (jFormattedTextField6.getText().length() == 0)
        {jFormattedTextField6.setText("0");}     
        if (jFormattedTextField7.getText().length() == 0)
        {jFormattedTextField7.setText("0");}
        if (jFormattedTextField8.getText().length() == 0)
        {jFormattedTextField8.setText("0");}
        if (jFormattedTextField10.getText().length() == 0)
        {jFormattedTextField10.setText("0");}
        
        double receivingYards = Double.parseDouble(jFormattedTextField9.getText());
        double passingYards = Double.parseDouble(jFormattedTextField1.getText());
        double rushingYards = Double.parseDouble(jFormattedTextField3.getText());
        double interceptions = Double.parseDouble(jFormattedTextField2.getText());
        double tdPasses = Double.parseDouble(jFormattedTextField4.getText());
        double tdCatches = Double.parseDouble(jFormattedTextField5.getText());
        double tdRuns = Double.parseDouble(jFormattedTextField6.getText());
        double twoPointConversions = Double.parseDouble(jFormattedTextField7.getText());
        double fumbles = Double.parseDouble(jFormattedTextField8.getText());
        double receptions = Double.parseDouble(jFormattedTextField10.getText());
               
        
        scores[0] = receivingYards * ruleset.getReceivingMod();
        scores[1] = passingYards * ruleset.getPassingMod();
        scores[2] = rushingYards * ruleset.getRushingMod();
        scores[3] = interceptions * ruleset.getIntMod();
        scores[4] = tdPasses * ruleset.gettdPassMod();
        scores[5] = tdCatches * ruleset.gettdCatchMod();
        scores[6] = tdRuns * ruleset.gettdRunMod();
        scores[7] = twoPointConversions * ruleset.gettwoPointMod();
        scores[8] = fumbles * ruleset.getfumbleMod();
        scores[9] = receptions * ruleset.getCatchMod();
        
        
       
        double sum = 0;
        for (double value : scores) 
        {
            System.out.println(value);
            sum += value;
        }
        Scanner playername = new Scanner (System.in);
        System.out.print ("What is the player's name?: ");
        String getName = playername.nextLine();
        
        
        result = sum;
        if(player.getPlayerName().equals(getName))
        {
            player.addScore(result);
            player.viewStats();
        }
        else
            {
                player.setPlayerName(getName);
                player.addScore(result);
                player.viewStats();
                Scanner input = new Scanner(System.in);
                 System.out.print("Would you like to add this player to your team?: ");
                    String userChoice = input.nextLine();
                if (userChoice.equals("yes"))
                   {
                     team.addToRoster(player);
                     System.out.println("Player added to team!");
                    }
                else if (userChoice.equals("Yes"))
                {
                    team.addToRoster(player);
                    System.out.println("Player added to team!");
                }
                else
                {
                }
            }
        updateDisplay();
        
        
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int i = ruleset.getRulesetSetting();
        
        switch (i) {         
            case 1:
                ruleset.setRulesetSetting(2);
                i = ruleset.getRulesetSetting();
                break;
            case 2:
                ruleset.setRulesetSetting(3);
                i = ruleset.getRulesetSetting();
                break;
            case 3:
                ruleset.setRulesetSetting(1);
                i = ruleset.getRulesetSetting();
                break;
            
        }
        ruleset.setRuleset(i);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem about;
    private javax.swing.JTextField display;
    private javax.swing.JButton jButton23;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField10;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JFormattedTextField jFormattedTextField7;
    private javax.swing.JFormattedTextField jFormattedTextField8;
    private javax.swing.JFormattedTextField jFormattedTextField9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem quit;
    // End of variables declaration//GEN-END:variables
}
